export { default as Home } from './Home'
export { default as Login } from './Login'
export {default as Signup} from './Signup'
export {default as UserHome} from './UserHome'
export {default as History} from './History'
export {default as Scanner} from './Scanner'
export {default as FriendsList} from './FriendsList'
export {default as LoadingPage} from './LoadingPage'
